import React from "react";
import styles from '../styles/Home.module.css'
import ReactDOM from "react-dom";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";

const SignupSchema = yup.object().shape({
    firstName: yup.string().required('وارد کردن نام الزامیست'),
    lastName: yup.string().required('وارد کردن نام خانوادگی الزامیست'),
    email: yup.string().required('ایمیل الزامیست').email('فرمت ایمیل را رعایت کنید'),
});

export default function Home() {

    const {register, handleSubmit, formState: { errors }} = useForm({resolver: yupResolver(SignupSchema)});
    const onSubmit = (data) => {
        console.log(data)
    };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossOrigin="anonymous" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-100 d-flex justify-content-center'>
        <div className={styles.formBox} dir='rtl'>
            <form onSubmit={handleSubmit(onSubmit)}>
                <div className='row'>
                <div className='col-12 col-md-6'>
                    <label  className='mt-4 mb-2'>نام</label>
                    <input {...register("firstName")} className='form-control' />
                    {errors.firstName && <p className='text-danger mt-3'>{errors.firstName.message}</p>}
                </div>
                <div className='col-12 col-md-6'>
                    <label  className='mt-4 mb-2'>نام خانوادگی</label>
                    <input {...register("lastName")} className='form-control' />
                    {errors.lastName && <p  className='text-danger mt-3'>{errors.lastName.message}</p>}
                </div>
                    <div className='col-12'>
                        <label  className='mt-4 mb-2'>ایمیل</label>
                        <input type='email' {...register("email")} className='form-control' />
                        {errors.email && <p  className='text-danger mt-3'>{errors.email.message}</p>}
                    </div>
                    <div className='col-12 col-md-6 mx-auto'>
                        <label className='mt-4 mb-2'>توضیحات</label>
                        <textarea  name="desc" cols="30" rows="10" className='form-control'>

                        </textarea>
                    </div>
                    <div className='col-8 mx-auto mt-5'>
                        <input
                            type="submit"
                            className='btn btn-success w-100'/>
                    </div>
                </div>
            </form>
        </div>
      </div>

    </div>
  )
}
